import { z } from "zod";

/* ------------------------------------------------------------ API responses */

const namedSchema = z
  .object({ id: z.number().int(), name: z.string().nullable().optional() })
  .nullable()
  .optional();

/** One row of `/admin/users`, and the same shape a single member comes back as. */
export const memberRowSchema = z.object({
  id: z.number().int(),
  name: z.string().nullable().optional(),
  last_name: z.string().nullable().optional(),
  full_name: z.string().nullable().optional(),
  /** The login name. On this site it is always a mobile number. */
  username: z.string(),
  phone: z.string().nullable().optional(),
  other_phones: z.array(z.string()).default([]),
  email: z.string().nullable().optional(),
  photo: z.string().nullable().optional(),
  /** Membership code, generated by the backend from the city. */
  code: z.string().nullable().optional(),
  status: z.string().default("1"),
  /** `has_role` and `status` together — the backend's own `isActive()`. */
  active: z.boolean().default(false),
  has_role: z.boolean().default(false),
  roles: z.array(z.string()).default([]),
  branch: namedSchema,
  city: namedSchema,
  created_at_jalali: z.string().default(""),
});

/** The extra columns only the single-member call returns, for the edit form. */
export const memberDetailSchema = memberRowSchema.extend({
  city_id: z.number().int().nullable().optional(),
  branch_id: z.number().int().nullable().optional(),
  gender: z.string().nullable().optional(),
  title: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  alias: z.string().nullable().optional(),
  activity_estate_type: z.array(z.number().int()).default([]),
  districts: z.array(z.number().int()).default([]),
});

export const membersResponseSchema = z.object({
  status: z.literal("success"),
  result: z.object({
    items: z.array(memberRowSchema).default([]),
    meta: z
      .object({
        page: z.number().int().default(1),
        per_page: z.number().int().default(20),
        total: z.number().int().nonnegative().default(0),
        last_page: z.number().int().nonnegative().default(1),
      })
      .default({ page: 1, per_page: 20, total: 0, last_page: 1 }),
  }),
});

export const memberResponseSchema = z.object({
  status: z.literal("success"),
  result: memberDetailSchema,
});

const optionSchema = z.object({
  value: z.union([z.string(), z.number()]).transform(String),
  title: z.string(),
});

/**
 * `roles` is filtered by the backend's own `canAssignRole()`, so this list is
 * already "what you are allowed to hand out" rather than every role there is —
 * a secretary never sees the accountant role here.
 */
export const memberFormOptionsResponseSchema = z.object({
  status: z.literal("success"),
  result: z.object({
    roles: z.array(optionSchema.extend({ id: z.number().int().optional() })).default([]),
    branches: z.array(optionSchema).default([]),
    statuses: z.array(optionSchema).default([]),
  }),
});

export const memberSavedResponseSchema = z.object({
  status: z.literal("success"),
  result: z.union([memberRowSchema, z.object({ id: z.number().int() })]).optional(),
});

/* --------------------------------------------------------------------- form */

const PERSIAN_DIGITS = /[۰-۹٠-٩]/g;

export function toEnglishDigits(value: string): string {
  return value.replace(PERSIAN_DIGITS, (digit) => {
    const persian = "۰۱۲۳۴۵۶۷۸۹".indexOf(digit);
    return String(persian >= 0 ? persian : "٠١٢٣٤٥٦٧٨٩".indexOf(digit));
  });
}

const digits = z.string().transform((value) => toEnglishDigits(value).trim());

/**
 * The member form.
 *
 * The rules are the backend's, from `AdminUserController`: a name and surname,
 * a login name unique among role holders, at least one role, and a password of
 * six characters or more. Password is the one field that differs between the
 * two uses — required when creating, and on an edit an empty box means "leave
 * it alone" rather than "clear it" — so the check lives in a `superRefine`
 * that knows which of the two it is.
 */
export const memberFormSchema = z
  .object({
    mode: z.enum(["create", "edit"]),
    name: z.string().trim().max(120, "نام طولانی است"),
    last_name: z.string().trim().max(120, "نام خانوادگی طولانی است"),
    username: digits.pipe(
      z.string().min(1, "نام کاربری را وارد کنید").max(60, "نام کاربری طولانی است"),
    ),
    password: z.string(),
    roles: z.array(z.string()),
    phone: digits.pipe(z.string().max(20, "شماره طولانی است")),
    other_phones: z.string().trim().max(200),
    email: z.string().trim().max(190),
    gender: z.string(),
    branch_id: z.string(),
    city_id: z.string(),
    status: z.string(),
    title: z.string().trim().max(190, "عنوان طولانی است"),
    description: z.string().trim().max(2000, "توضیحات طولانی است"),
    districts: z.array(z.string()),
    activity_estate_type: z.array(z.string()),
  })
  .superRefine((data, context) => {
    if (data.mode === "create" && data.name === "") {
      context.addIssue({ code: "custom", path: ["name"], message: "نام را وارد کنید" });
    }
    if (data.mode === "create" && data.last_name === "") {
      context.addIssue({
        code: "custom",
        path: ["last_name"],
        message: "نام خانوادگی را وارد کنید",
      });
    }
    if (data.roles.length === 0) {
      context.addIssue({
        code: "custom",
        path: ["roles"],
        message: "دست‌کم یک نقش انتخاب کنید",
      });
    }
    if (data.mode === "create" && data.password.length < 6) {
      context.addIssue({
        code: "custom",
        path: ["password"],
        message: "رمز عبور باید دست‌کم ۶ نویسه باشد",
      });
    }
    if (data.mode === "edit" && data.password !== "" && data.password.length < 6) {
      context.addIssue({
        code: "custom",
        path: ["password"],
        message: "رمز تازه باید دست‌کم ۶ نویسه باشد",
      });
    }
    if (data.email !== "" && !/^\S+@\S+\.\S+$/.test(data.email)) {
      context.addIssue({ code: "custom", path: ["email"], message: "ایمیل معتبر نیست" });
    }
  });

export type MemberRow = z.infer<typeof memberRowSchema>;
export type MemberDetail = z.infer<typeof memberDetailSchema>;
export type MemberFormOptions = z.infer<
  typeof memberFormOptionsResponseSchema
>["result"];
export type MemberFormValues = z.infer<typeof memberFormSchema>;

/** Everything the list can be narrowed by, as the API spells it. */
export type MemberFilters = {
  name: string;
  username: string;
  phone: string;
  status: string;
  branch_id: string;
  role_id: string;
};

export const defaultMemberFilters: MemberFilters = {
  name: "",
  username: "",
  phone: "",
  status: "",
  branch_id: "",
  role_id: "",
};
