"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Home, Send, Sparkles, UserRound } from "lucide-react";
import { crmMatches } from "@/app/panel/_data/crm";
import { panelProperties,panelRequests } from "@/app/panel/_data/panel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Typography } from "@/components/ui/typography";
import { routes } from "@/lib/routes";
export function MatchBoard(){const [sent,setSent]=useState<string[]>(crmMatches.filter((item)=>item.status!=="new").map((item)=>item.id));return <div className="grid gap-3">{crmMatches.map((match)=>{const request=panelRequests.find((item)=>item.id===match.requestId)!;const property=panelProperties.find((item)=>item.listing.id===match.propertyId)!.listing;const isSent=sent.includes(match.id);return <Card key={match.id}><CardContent className="p-4"><div className="grid items-center gap-4 lg:grid-cols-[1fr_auto_1fr_auto]"><div className="flex gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600"><UserRound /></span><div><Typography variant="small">متقاضی</Typography><Typography as="h2" variant="h4">{request.values.name}</Typography><Typography variant="small" className="mt-1">{request.values.requestType==="buy"?"خرید":"اجاره"} · {request.values.districts[0]}</Typography><Link href={routes.panel.request(request.id)} className="mt-2 inline-flex items-center gap-1 text-xs text-brand">جزئیات تقاضا<ArrowLeft className="size-3" /></Link></div></div><div className="flex flex-col items-center"><span className="flex size-14 items-center justify-center rounded-full bg-brand text-lg font-bold text-white">{match.score.toLocaleString("fa-IR")}٪</span><Typography variant="small" className="mt-1">امتیاز تطبیق</Typography></div><div className="flex gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-600"><Home /></span><div><Typography variant="small">ملک پیشنهادی</Typography><Typography variant="h4">{property.title}</Typography><Typography variant="small" className="mt-1">{property.district} · {property.price}</Typography><div className="mt-2 flex flex-wrap gap-1">{match.reasons.map((reason)=><Badge key={reason} variant="outline">{reason}</Badge>)}</div></div></div><div><Button size="sm" variant={isSent?"outline":"default"} onClick={()=>setSent((current)=>current.includes(match.id)?current:[...current,match.id])}>{isSent?<CheckCircle2 />:<Send />}{isSent?"ارسال‌شده":"ارسال به مشتری"}</Button></div></div></CardContent></Card>})}<div className="sr-only"><Sparkles />تطبیق هوشمند</div></div>}

