"use client";
import { useState } from "react";
import { CalendarDays,CheckCircle2,Clock,MapPin,Plus,UserRound,X } from "lucide-react";
import { crmAppointments,type AppointmentStatus } from "@/app/panel/_data/crm";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Typography } from "@/components/ui/typography";
const statusMeta:Record<AppointmentStatus,{label:string;variant:"default"|"secondary"|"destructive"}>={scheduled:{label:"برنامه‌ریزی‌شده",variant:"default"},done:{label:"انجام‌شده",variant:"secondary"},cancelled:{label:"لغوشده",variant:"destructive"}};
export function AppointmentBoard(){const [items,setItems]=useState(crmAppointments);const [showForm,setShowForm]=useState(false);const [title,setTitle]=useState("");const [date,setDate]=useState("");const add=()=>{if(!title||!date)return;setItems((current)=>[{id:`ap-${Date.now()}`,title,date,time:"—",location:"تعیین نشده",customer:"تعیین نشده",agent:"حامد کریمی",status:"scheduled"},...current]);setShowForm(false);setTitle("");setDate("")};return <div>{showForm&&<Card className="mb-4 border-brand/30"><CardContent className="p-4"><div className="mb-4 flex items-center justify-between"><Typography variant="h4">قرار جدید</Typography><Button size="icon-sm" variant="ghost" onClick={()=>setShowForm(false)}><X /></Button></div><div className="grid gap-4 sm:grid-cols-[1fr_220px_auto]"><div><Label htmlFor="appointment-title" className="mb-2">عنوان قرار</Label><Input id="appointment-title" value={title} onChange={(event)=>setTitle(event.target.value)} placeholder="مثلاً بازدید ملک پردیسان" /></div><div><Label htmlFor="appointment-date" className="mb-2">تاریخ و ساعت</Label><Input id="appointment-date" type="datetime-local" value={date} onChange={(event)=>setDate(event.target.value)} /></div><Button className="self-end" onClick={add}>ذخیره قرار</Button></div></CardContent></Card>}<div className="mb-4 flex justify-end"><Button onClick={()=>setShowForm(true)}><Plus />قرار جدید</Button></div><div className="grid gap-3">{items.map((item)=>{const meta=statusMeta[item.status];return <Card key={item.id}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><span className="flex size-12 shrink-0 flex-col items-center justify-center rounded-xl bg-brand/10 text-brand"><CalendarDays className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Typography as="h2" variant="h4">{item.title}</Typography><Badge variant={meta.variant}>{meta.label}</Badge></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span className="flex items-center gap-1"><Clock className="size-3.5" />{item.date}، {item.time}</span><span className="flex items-center gap-1"><MapPin className="size-3.5" />{item.location}</span><span className="flex items-center gap-1"><UserRound className="size-3.5" />{item.customer}</span></div></div>{item.status==="scheduled"&&<Button size="sm" variant="outline" onClick={()=>setItems((current)=>current.map((entry)=>entry.id===item.id?{...entry,status:"done"}:entry))}><CheckCircle2 />انجام شد</Button>}</CardContent></Card>})}</div></div>}

